### ISSUE TITLE
win10测试无法通过

### ISSUE THREAD

**Issue by fanmeide** [oakboat/HyperCE#2]
运行环境：vm虚拟机，win10 1909版
    if (strstr(process_name, "cheatengine") || strstr(process_name, "HyperCE"))
    {
        DbgPrint("process_name: %s. DesiredAccess: %lu, AccessMode: %u\n", process_name, DesiredAccess, AccessMode);
        NTSTATUS status = ObReferenceObjectByHandleWithTagHookTrampoline(Handle, 0, ObjectType, KernelMode, Tag, Object, HandleInformation);
        DbgPrint("Returned status: %08X\n", status);
        return status;
    }
   钩子处加入调试代码如上，

    test也加了调试代码
        if (ReadProcessMemory(hProcess, (LPCVOID)baseAddress, buffer, sizeof(buffer), &bytesRead)) {
        std::cout << "Memory content at base address: ";
        // Print the memory content in hexadecimal format
        for (SIZE_T i = 0; i < bytesRead; i++) {
            std::cout << std::hex << (int)buffer[i] << " ";
        }
        std::cout << std::dec << std::endl; // Reset the output to decimal format
    }
    else {

        DWORD dwLastError = GetLastError();
        if (dwLastError != 0) {
            std::cerr << "ReadProcessMemory failed. LastError: " << dwLastError << std::endl;
        }
    }
    
    运行后：钩子处的调试是正确的 ：
    process_name: cheatengine.ex. DesiredAccess: 8, AccessMode: 1
    但是test的结果一直是ReadProcessMemory failed. LastError: 5
  
  学习内核不是太久，请指导一下，谢谢

**Comment by oakboat** [comment]
应该是新版win10函数是ObpReferenceObjectByHandleWithTag了

**Comment by fanmeide** [comment]
> 应该是新版win10函数是ObpReferenceObjectByHandleWithTag了

ObReferenceObjectByHandleWithTag属于wdm.h
在其中没有找到ObpReferenceObjectByHandleWithTag，请问这种情况应该怎么做喃？

**Comment by oakboat** [comment]
修好了 https://github.com/oakboat/HyperCE/commit/2b40de48909d673c229aedb76beab48f9c726d6a
测试下
